### ISSUE TITLE
show class's mixins

### ISSUE THREAD

**Issue by wkeese** [wkeese/old-api-viewer#10]
The old viewer showed the inheritance hierarchy, for example:

Object » dijit._Widget » dijit.layout.ContentPane » dijit.Dialog

Strangely it didn't show mixins, only the chain of superclasses.

Anyway, probably we should should all the mixins.

**Comment by ttrenka** [comment]
This was done for a reason, mainly because when you start adding mixins that happen deeper in the chain, the _actual_ inheritance chain ends up getting very muddy.

Mixins for an object are currently listed as the last item at the top of a page, before the field lists are added. See http://dojotoolkit.org/api/1.7/dijit/form/FilteringSelect for an example.

**Comment by wkeese** [comment]
Ah I see, didn't notice the mixins listing before.

I agree that listing the whole inheritance tree would be overwhelming, I just meant that the direct mixins should be listed.   I must have removed that code inadvertently, and will put it back.
