### ISSUE TITLE
Double Scroll Bars in TreeView

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#14]
Adrian states: 

> Just noticed that in some browsers (Chrome 19 and IE9, but not FF13) a double scrollbar appears when either using browser's zoom, or when using the splitter to reduce the width of the TOC pane.

**Comment by AdrianVasiliu** [comment]
And this holds for both http://bill.dojotoolkit.org/api/ and http://dojotoolkit.org/api/ .

**Comment by ttrenka** [comment]
This is either a Dijit bug or a bug in the way I set up the content panes on the left side of the viewer, and has been there since the viewer's original launch.  I didn't do anything special in terms of CSS or whatnot with that IIRC, so it might be worth it to be looking at Dijit itself for this one.

**Comment by wkeese** [comment]
I can easily reproduce this against 1.7 (both Google CDN, and local checkout), but it's working against trunk (at least for me).   So I don't think it's worth investigating further.

As for the viewer itself, it does have an unnecessary ContentPane (i.e. the Tree could be a direct child of the Accordion), but that's not a fatal error.

**Comment by ttrenka** [comment]
You could remove the unnecessary ContentPane; that's in index.php.  I seem to remember trying it and having issues but I wrote this originally against 1.5...and you are undoubtedly the Dijit master =)
