### ISSUE TITLE
Namespaces should be Packages

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#19]
The API reviewer refers to things as "Namespaces" when it should be updated to reflect "Packages" in the "modern" Dojo world.

Both the ICON and the hints need to be changed.

**Comment by wkeese** [comment]
Hmm, I don't think dojo/cldr is a package, do you?

**Comment by kitsonk** [comment]
Maybe, although it would be more appropriate to call it a package that
contains modules and non-modules, but dojo/promise, dojo/request,
dojo/router, dojo/errors, dojo/store and dojo/_base aren't namespaces.
 Namespaces seems very anti-AMD-ish.

On 1 July 2012 13:41, Bill Keese <
reply@reply.github.com

**Comment by wkeese** [comment]
dojo/promise, dojo/router etc. aren't really anything, they are just a UI abstraction used to display a tree of modules rather than a flat list of modules.

AMD doesn't have any concept of hierarchy.

**Comment by wkeese** [comment]
Probably it should just be using a folder icon, so that it doesn't seem like dojo/cldr is a "real thing".

And on a related note, for cases like dojo/date, which is both a module and the folder where dojo/date/locale lives, perhaps the tree should have two TreeNodes, one for the module and another for the folder.
