### ISSUE TITLE
Constructor Improvements

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#20]
The constructor API for objects should be at the top of the page for Classes, instead of just being listed as a method of the class.

**Comment by ttrenka** [comment]
There's a problem with doing that...mainly because something explicitly marked as a constructor is usually the result of something dojo/_base/declare. In theory, because of the way declare works, the constructor method is actually a method of the returned object, as opposed to being a function that attaches things to the activation object that is returned from a "standard" JS constructor.

It's one of those quirks of JS that is very hard to get around programmatically.

**Comment by kitsonk** [comment]
I was noticing that in the current form of the API viewer, nothing was getting marked a constructor, although js-doc-parser can flag something as a constructor.  I need to investigate if those things that are getting flagged as a constructor are just not showing the right icon.  If they aren't, then it will be an API viewer thing, if they are simply not getting flagged, then obviously it is a limitation of the js-doc-parser.

**Comment by wkeese** [comment]
@kitsonk - you might want to tweak the CSS etc. for how this shows up, but basically it's working :-)
