### ISSUE TITLE
Bad user experience on slow networks

### ISSUE THREAD

**Issue by dylans** [wkeese/old-api-viewer#47]
When using the API viewer on a slow network, the request to load the items under dojo or dijit may take 5-15 seconds, but there's no user feedback that the tree is loading. This may lead a user to click on the tree again, which then would close the tree.

A possible solution would be to give some sort of user feedback that the tree is loading, etc.

**Comment by wkeese** [comment]
Tree does have a loading indicator but I guess not for the root node.   So
probably it should do the XHR to load the data not in the getRoot() call
but after that, when it gets the first level of children.  Or fix Tree to
show the indicator for the root node too.

**Comment by wkeese** [comment]
OK, fixed in http://bugs.dojotoolkit.org/ticket/16302.

To further speed things up, I'm sure the size of the tree.json file could be reduced, and we could even do lazy loading of the Tree data.    It's just a question of diminishing returns, since the Tree already loads quickly over a broadband connection.
